centre_medic_back_homepage:
    path:     /
    defaults: { _controller: BackBundle:Default:index }
centre_medic_back_pacients_new:
    path:     /new/
    defaults: { _controller: BackBundle:Pacients:new }
centre_medic_back_pacients_view:
    path:     /view/{id}
    defaults: { _controller: BackBundle:Pacients:view }
centre_medic_back_pacients_edit:
    path:     /edit/{id}
    defaults: { _controller: BackBundle:Pacients:edit }
centre_medic_back_pacients_delete:
    path:     /delete/{id}
    defaults: { _controller: BackBundle:Pacients:delete }
centre_medic_llista_back_pacients:
    path:     /llista_pacients
    defaults: { _controller: BackBundle:Pacients:llistaPacients }
centre_medic_llista_back_metges:
    path:     /llista_metges
    defaults: { _controller: BackBundle:Metges:llistaMetges }
centre_medic_llista_back_visites:
    path:     /llista_visites
    defaults: { _controller: BackBundle:Visites:llistaVisites }
