
centre_medic_back_pacients_new:
    path:     /new/
    defaults: { _controller: BackBundle:Pacients:new }
centre_medic_back_pacients_view:
    path:     /view/{id}
    defaults: { _controller: BackBundle:Pacients:view }
centre_medic_back_pacients_edit:
    path:     /edit/{id}
    defaults: { _controller: BackBundle:Pacients:edit }
centre_medic_back_pacients_delete:
    path:     /delete/{id}
    defaults: { _controller: BackBundle:Pacients:delete }
